version: 2

pipeline:
  steps:
    - step:
        phase: install
        name: clone
        cache: []
        image: maxitg/set-replace:ci
        auth:
          username: maxitg
          password: $DOCKERHUB_PASSWORD
        commands:
          - echo "cloned"

    - step:
        phase: build
        name: build
        commands:
          - ./build.wls
          - ./install.wls

    - step:
        phase: test
        name: test
        commands:
          - ./test.wls
