version: 2

pipeline:
  steps:
    - step:
        phase: install
        name: clone
        cache: []
        image: maxitg/set-replace:ci
        commands:
          - echo "cloned"

    - step:
        phase: build
        name: build
        commands:
          - ./build.wls
          - ./install.wls
          # Install twice to check re-installation.
          - ./install.wls

    - step:
        phase: test
        name: test
        commands:
          - ./test.wls
