version: 2
jobs:
  wolfram-language:
    docker:
      - image: maxitg/set-replace-wl-ci:12.1.1
        auth:
          username: maxitg
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout

      - run:
          name: Build
          command: ./build.wls

      - store_artifacts:
          path: ./LibraryResources/

      - run:
          name: Install
          command: ./install.wls

      - store_artifacts:
          path: ./BuiltPaclets/

      - run:
          name: Reinstall
          command: ./install.wls

      - run:
          name: Build libSetReplace with LibraryLink
          command: |
            mkdir build
            cd build
            cmake .. -DSET_REPLACE_BUILD_TESTING=OFF \
                     -DSET_REPLACE_WITH_MATHEMATICA=ON \
                     -DSET_REPLACE_ENABLE_ALLWARNINGS=ON
            cmake --build .

      - run:
          name: Test
          command: ./.circleci/test.sh
  cpp:
    docker:
      - image: maxitg/set-replace-cpp-ci

    steps:
      - checkout

      - run:
          name: Lint
          command: ./lint.sh

      - run:
          name: Build
          command: |
            mkdir build
            cd build
            cmake .. -DSET_REPLACE_BUILD_TESTING=ON \
                     -DSET_REPLACE_WITH_MATHEMATICA=OFF \
                     -DSET_REPLACE_ENABLE_ALLWARNINGS=ON
            cmake --build .

      - run:
          name: Test
          command: ./libSetReplaceTest.sh

workflows:
  version: 2
  build-and-test:
    jobs:
      - wolfram-language
      - cpp
